### ISSUE TITLE
gv.Path doesn't have legend labels

### ISSUE THREAD

**Issue by ahuang11** [holoviz/geoviews#388] opened 2019-11-21 20:42 UTC
```
import geoviews as gv
gv.extension('bokeh')
gv.Path(([0, 1, 2], [0, 5, 6]), label='blue') * gv.Path(([0, 1, 2], [0, 2, 6]), label='red')
```

Output:
![image](https://user-images.githubusercontent.com/15331990/69375050-039fe300-0c6d-11ea-8973-4627edb7cf64.png)

Expected:
![image](https://user-images.githubusercontent.com/15331990/69375074-10243b80-0c6d-11ea-85b5-65652c6e0706.png)

**Comment by philippjfr** [comment] 2020-01-06 18:52
Duplicate of https://github.com/holoviz/holoviews/issues/2601

**Closed by philippjfr** 2020-01-06 18:52 UTC
Labels: TRIAGE
