### ISSUE TITLE
TypeError when building animation from netcdf

### ISSUE THREAD

**Issue by fccoelho** [holoviz/geoviews#327] opened 2019-05-07 18:34 UTC
I am getting a time error when I try to run the following code to animate a series of geotifs saved to netcdf with xarray.

```python
with xr.open_dataset('time_series.nc', decode_times=False) as da:
        dataset = gv.Dataset(da)
        ensemble = dataset.to(gv.Image, ['x', 'y'])
        gv.output(ensemble.opts(cmap=opt.cmap, colorbar=True, fig_size=200, backend='matplotlib'), backend='matplotlib')
```
the code that creates the netcdf file is:

```python
import xarray as xr
with xr.concat([xr.open_rasterio(f, chunks=chunks) for f in filenames], dim=time) as da:
        da.to_netcdf('time_series.nc')
```
and filenames is a list of pre-downloaded geotiffs.

here is the full error:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/IPython/core/formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

/usr/local/lib/python3.6/dist-packages/holoviews/core/dimension.py in _repr_mimebundle_(self, include, exclude)
   1291         combined and returned.
   1292         """
-> 1293         return Store.render(self)
   1294 
   1295 

/usr/local/lib/python3.6/dist-packages/holoviews/core/options.py in render(cls, obj)
   1360         data, metadata = {}, {}
   1361         for hook in hooks:
-> 1362             ret = hook(obj)
   1363             if ret is None:
   1364                 continue

/usr/local/lib/python3.6/dist-packages/holoviews/ipython/display_hooks.py in pprint_display(obj)
    275     if not ip.display_formatter.formatters['text/plain'].pprint:
    276         return None
--> 277     return display(obj, raw_output=True)
    278 
    279 

/usr/local/lib/python3.6/dist-packages/holoviews/ipython/display_hooks.py in display(obj, raw_output, **kwargs)
    251     elif isinstance(obj, (HoloMap, DynamicMap)):
    252         with option_state(obj):
--> 253             output = map_display(obj)
    254     elif isinstance(obj, Plot):
    255         output = render(obj)

/usr/local/lib/python3.6/dist-packages/holoviews/ipython/display_hooks.py in wrapped(element)
    140         try:
    141             max_frames = OutputSettings.options['max_frames']
--> 142             mimebundle = fn(element, max_frames=max_frames)
    143             if mimebundle is None:
    144                 return {}, {}

/usr/local/lib/python3.6/dist-packages/holoviews/ipython/display_hooks.py in map_display(vmap, max_frames)
    200         return None
    201 
--> 202     return render(vmap)
    203 
    204 

/usr/local/lib/python3.6/dist-packages/holoviews/ipython/display_hooks.py in render(obj, **kwargs)
     63         renderer = renderer.instance(fig='png')
     64 
---> 65     return renderer.components(obj, **kwargs)
     66 
     67 

/usr/local/lib/python3.6/dist-packages/holoviews/plotting/renderer.py in components(self, obj, fmt, comm, **kwargs)
    319             plot = obj
    320         else:
--> 321             plot, fmt = self._validate(obj, fmt)
    322 
    323         widget_id = None

/usr/local/lib/python3.6/dist-packages/holoviews/plotting/renderer.py in _validate(self, obj, fmt, **kwargs)
    218         if isinstance(obj, tuple(self.widgets.values())):
    219             return obj, 'html'
--> 220         plot = self.get_plot(obj, renderer=self, **kwargs)
    221 
    222         fig_formats = self.mode_formats['fig'][self.mode]

/usr/local/lib/python3.6/dist-packages/holoviews/plotting/renderer.py in get_plot(self_or_cls, obj, renderer, **kwargs)
    205             init_key = tuple(v if d is None else d for v, d in
    206                              zip(plot.keys[0], defaults))
--> 207             plot.update(init_key)
    208         else:
    209             plot = obj

/usr/local/lib/python3.6/dist-packages/holoviews/plotting/mpl/plot.py in update(self, key)
    242         if len(self) == 1 and ((key == 0) or (key == self.keys[0])) and not self.drawn:
    243             return self.initialize_plot()
--> 244         return self.__getitem__(key)
    245 
    246 

/usr/local/lib/python3.6/dist-packages/holoviews/plotting/plot.py in __getitem__(self, frame)
    256         if isinstance(frame, int) and frame > len(self):
    257             self.param.warning("Showing last frame available: %d" % len(self))
--> 258         if not self.drawn: self.handles['fig'] = self.initialize_plot()
    259         if not isinstance(frame, tuple):
    260             frame = self.keys[frame]

/usr/local/lib/python3.6/dist-packages/holoviews/plotting/mpl/plot.py in wrapper(self, *args, **kwargs)
     46     def wrapper(self, *args, **kwargs):
     47         with _rc_context(self.fig_rcparams):
---> 48             return f(self, *args, **kwargs)
     49     return wrapper
     50 

/usr/local/lib/python3.6/dist-packages/holoviews/plotting/mpl/element.py in initialize_plot(self, ranges)
    510 
    511         return self._finalize_axis(self.keys[-1], element=element, ranges=ranges,
--> 512                                    **axis_kwargs)
    513 
    514 

/usr/local/lib/python3.6/dist-packages/geoviews/plotting/mpl/__init__.py in _finalize_axis(self, *args, **kwargs)
    106 
    107     def _finalize_axis(self, *args, **kwargs):
--> 108         ret = super(GeoPlot, self)._finalize_axis(*args, **kwargs)
    109         axis = self.handles['axis']
    110         if self.show_grid:

/usr/local/lib/python3.6/dist-packages/holoviews/plotting/mpl/element.py in _finalize_axis(self, key, element, title, dimensions, ranges, xticks, yticks, zticks, xlabel, ylabel, zlabel)
    188 
    189         if not subplots and not self.drawn:
--> 190             self._finalize_artist(element)
    191 
    192         self._execute_hooks(element)

/usr/local/lib/python3.6/dist-packages/holoviews/plotting/mpl/element.py in _finalize_artist(self, element)
    726             dims = [h for k, h in self.handles.items() if k.endswith('color_dim')]
    727             for d in dims:
--> 728                 self._draw_colorbar(element, d)
    729 
    730 

/usr/local/lib/python3.6/dist-packages/holoviews/plotting/mpl/element.py in _draw_colorbar(self, element, dimension, redraw)
    741         if position is None or not redraw:
    742             if redraw:
--> 743                 fig.canvas.draw()
    744             bbox = axis.get_position()
    745             l, b, w, h = bbox.x0, bbox.y0, bbox.width, bbox.height

/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_agg.py in draw(self)
    400         toolbar = self.toolbar
    401         try:
--> 402             self.figure.draw(self.renderer)
    403             # A GUI class may be need to update a window using this draw, so
    404             # don't forget to call the superclass.

/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py in draw(self, renderer)
   1647 
   1648             mimage._draw_list_compositing_images(
-> 1649                 renderer, self, artists, self.suppressComposite)
   1650 
   1651             renderer.close_group('figure')

/usr/local/lib/python3.6/dist-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

/usr/local/lib/python3.6/dist-packages/cartopy/mpl/geoaxes.py in draw(self, renderer, inframe)
    386 
    387         return matplotlib.axes.Axes.draw(self, renderer=renderer,
--> 388                                          inframe=inframe)
    389 
    390     def __str__(self):

/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2626             renderer.stop_rasterizing()
   2627 
-> 2628         mimage._draw_list_compositing_images(renderer, self, artists)
   2629 
   2630         renderer.close_group('axes')

/usr/local/lib/python3.6/dist-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

/usr/local/lib/python3.6/dist-packages/matplotlib/collections.py in draw(self, renderer)
   1917                 offsets = np.column_stack([xs, ys])
   1918 
-> 1919         self.update_scalarmappable()
   1920 
   1921         if not transform.is_affine:

/usr/local/lib/python3.6/dist-packages/matplotlib/collections.py in update_scalarmappable(self)
    777             return
    778         if self._is_filled:
--> 779             self._facecolors = self.to_rgba(self._A, self._alpha)
    780         elif self._is_stroked:
    781             self._edgecolors = self.to_rgba(self._A, self._alpha)

/usr/local/lib/python3.6/dist-packages/matplotlib/cm.py in to_rgba(self, x, alpha, bytes, norm)
    286         x = ma.asarray(x)
    287         if norm:
--> 288             x = self.norm(x)
    289         rgba = self.cmap(x, alpha=alpha, bytes=bytes)
    290         return rgba

/usr/local/lib/python3.6/dist-packages/matplotlib/colors.py in __call__(self, value, clip)
    955             # ma division is very slow; we can take a shortcut
    956             resdat = result.data
--> 957             resdat -= vmin
    958             resdat /= (vmax - vmin)
    959             result = np.ma.array(resdat, mask=result.mask, copy=False)

TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('S32') dtype('S32') dtype('S32')
```

**Comment by ahuang11** [comment] 2019-05-22 02:10
It looks like some cmap issue?
What is `opt.cmap`?

**Comment by philippjfr** [comment] 2019-10-24 17:44
Are the tiffs something you can share?

**Comment by philippjfr** [comment] 2020-08-17 15:23
Closing as I cannot reproduce. Please reopen if you can share a reproducible example.

**Closed by philippjfr** 2020-08-17 15:23 UTC
Labels: needs info, type: bug
